import { ServiceItem, Testimonial, VideoTestimonial } from '../types';

export const AGENCY_SERVICES: ServiceItem[] = [
  {
    id: 'trafego-pago',
    title: 'Gestão de Tráfego Pago & Performance',
    shortDesc: 'Campanhas de alta precisão no Meta Ads (Facebook & Instagram) e Google Ads com foco obsessivo em ROI e menor custo por lead.',
    fullDesc: 'Criamos, gerenciamos e escalamos anúncios que colocam o seu produto ou serviço na frente de quem está pronto para comprar. Implementamos testes contínuos de criativos, otimização de lances e escala previsível.',
    category: 'trafego',
    tag: 'Mais Procurado',
    highlights: ['Meta Ads (Instagram / Facebook)', 'Google Ads & YouTube Ads', 'Retargeting Inteligente', 'Otimização Diária de CPA & ROAS'],
    deliverables: ['Configuração de Pixel & Conversions API', 'Pesquisa de Públicos & Concorrentes', 'Relatório Semanal de Desempenho', 'Painel de Métricas em Tempo Real'],
    recommendedFor: 'Empresas que precisam de fluxo diário de clientes qualificados.',
    iconName: 'TrendingUp',
  },
  {
    id: 'funil-palestras',
    title: 'Montagem de Funil de Palestras & Eventos',
    shortDesc: 'Estrutura completa para lotar salas de conferência, webinars e eventos ao vivo com público qualificado e conversão em massa.',
    fullDesc: 'Transformamos palestras em máquinas de fechamento de contratos de alto valor (High-Ticket). Da captação de inscritos até a automação de presença no WhatsApp e o pitch de vendas.',
    category: 'estrategia',
    tag: 'Alta Conversão',
    highlights: ['Página de Inscrição Magnética', 'Automação de Confirmação & Lembretes', 'Grupo VIP de Aquecimento no WhatsApp', 'Estratégia de Pitch & Oferta Irresistível'],
    deliverables: ['Landing page do evento', 'Sequência de copies para anúncios', 'Fluxos de mensagens automáticas', 'Scripts de fechamento pós-palestra'],
    recommendedFor: 'Palestrantes, mentores, consultores e infoprodutores.',
    iconName: 'Presentation',
  },
  {
    id: 'gestao-marketing',
    title: 'Gestão de Marketing & Growth 360°',
    shortDesc: 'Estratégia completa de posicionamento, aquisição de clientes e retenção para consolidar sua marca como líder de mercado.',
    fullDesc: 'Uma equipe completa atuando como o braço de marketing da sua empresa: unindo tráfego, design, copy e processos comerciais para gerar tração contínua e crescimento sólido.',
    category: 'estrategia',
    tag: 'Solução Completa',
    highlights: ['Planejamento Estratégico Trimestral', 'Alinhamento com Time Comercial', 'Branding de Resposta Direta', 'Análise de Concorrência & Oportunidades'],
    deliverables: ['Roadmap de crescimento', 'Auditorias quinzenais', 'Manual de posicionamento de marca', 'Acompanhamento de metas de faturamento'],
    recommendedFor: 'Pequenas e médias empresas que querem crescer com consistência.',
    iconName: 'Target',
  },
  {
    id: 'estruturacao-campanhas',
    title: 'Estruturação & Arquitetura de Campanhas',
    shortDesc: 'Construção técnica e estratégica de contas de anúncios preparadas para receber alto investimento sem bloqueios nem desperdício.',
    fullDesc: 'Desenvolvemos a espinha dorsal dos seus anúncios: esteira de testes de criativos (CBO/ABO), públicos semelhantes (Lookalike), públicos de interesse e exclusão de compradores.',
    category: 'trafego',
    tag: 'Escalabilidade',
    highlights: ['Estrutura Anti-Bloqueio & Contingência', 'Esteira de Testes Contínuos', 'Segmentação Avançada por Intenção', 'Escala Vertical e Horizontal'],
    deliverables: ['Mapeamento de públicos', 'Setup completo do Gerenciador de Anúncios', 'Tags e eventos do Google Tag Manager', 'Planilha de acompanhamento de testes'],
    recommendedFor: 'Negócios prontos para investir mais e multiplicar o volume de vendas.',
    iconName: 'Layers',
  },
  {
    id: 'landing-pages',
    title: 'Criação de Landing Pages de Alta Conversão',
    shortDesc: 'Páginas ultra-rápidas, com design impecável e copywriting persuasivo pensadas milimetricamente para transformar visitantes em compradores.',
    fullDesc: 'Nada de páginas lentas ou genéricas. Criamos páginas de vendas, páginas de captura e páginas institucionais com estética moderna, mobile-first e integradas diretamente ao seu WhatsApp e CRM.',
    category: 'web',
    tag: 'Design & Velocidade',
    highlights: ['Carregamento Instantâneo (< 1.5s)', 'Copywriting Persuasivo & Gatilhos', '100% Otimizado para Smartphones', 'Integração com WhatsApp e CRM'],
    deliverables: ['Design no Figma aprovado', 'Desenvolvimento em React / Tailwind', 'Hospedagem e domínio configurados', 'Rastreamento de cliques e eventos'],
    recommendedFor: 'Negócios que anunciam mas perdem clientes por páginas ruins ou lentas.',
    iconName: 'Layout',
  },
  {
    id: 'edicao-video',
    title: 'Edição de Vídeos Estratégicos para Anúncios',
    shortDesc: 'Vídeos dinâmicos para Reels, TikTok e YouTube Ads com ganchos fortes nos primeiros 3 segundos para reter e converter.',
    fullDesc: 'O criativo é responsável por 70% do sucesso dos anúncios. Editamos vídeos com legendas animadas, sonoplastia imersiva, b-rolls e cortes rápidos para quebrar o padrão de rolagem das redes.',
    category: 'video',
    tag: 'Criativos Magnéticos',
    highlights: ['Ganchos Fortes (Hooks) para os 3 Primeiros Segundos', 'Legendas Dinâmicas & Efeitos Visuais', 'Formatos 9:16 (Stories/Reels) e 16:9', 'Variações para Testes A/B'],
    deliverables: ['Pacote de criativos prontos para rodar', 'Variações de ganchos iniciais', 'Thumbnail de alta taxa de clique', 'Arquivos em alta definição 4K/1080p'],
    recommendedFor: 'Quem quer reduzir o custo do anúncio através de criativos melhores.',
    iconName: 'Video',
  },
  {
    id: 'gestao-redes',
    title: 'Gestão Estratégica de Redes Sociais & Contas',
    shortDesc: 'Posicionamento visual e editorial nas redes sociais alinhado às suas campanhas de tráfego para gerar autoridade e vendas diárias.',
    fullDesc: 'Não se trata de postar por postar. Construímos uma presença que passa confiança imediata ao lead que chega através dos anúncios, facilitando a decisão de compra.',
    category: 'video',
    tag: 'Autoridade Digital',
    highlights: ['Linha Editorial com Foco em Vendas', 'Design de Alto Padrão para Carrosséis e Posts', 'Otimização de Bio e Destaques Estratégicos', 'Calendário de Conteúdo Mensal'],
    deliverables: ['Feed estruturado', 'Templates customizados da marca', 'Copies persuasivas para legendas', 'Relatório de engajamento e conversão'],
    recommendedFor: 'Marcas e profissionais que desejam autoridade imediata no digital.',
    iconName: 'Share2',
  },
  {
    id: 'automacoes-crm',
    title: 'Automações Comerciais & Integração com CRM',
    shortDesc: 'Conecte seus anúncios ao WhatsApp, disparo de mensagens e sistema de gestão para nunca mais perder um lead por demora no atendimento.',
    fullDesc: 'Automatizamos o primeiro contato em menos de 1 minuto, triagem de leads, alertas para os vendedores e atualização de status no funil de vendas.',
    category: 'web',
    tag: 'Velocidade Comercial',
    highlights: ['Atendimento Instantâneo 24/7', 'Distribuição Inteligente de Leads', 'Integração WhatsApp Business API', 'Sincronização com Sistema de Gestão'],
    deliverables: ['Fluxo de automação configurado', 'Webhooks conectados ao banco de dados', 'Painel de notificações para a equipe', 'Treinamento rápido da equipe'],
    recommendedFor: 'Empresas que demoram para responder leads e perdem vendas.',
    iconName: 'Zap',
  },
  {
    id: 'consultoria-estrategica',
    title: 'Consultoria & Atendimento Personalizado',
    shortDesc: 'Sessões estratégicas 1 a 1 para diagnosticar gargalos, estruturar planos de ação customizados e acelerar seu faturamento.',
    fullDesc: 'Análise profunda dos seus números, produtos, esteira de vendas e funis. Entregamos um plano passo a passo com acompanhamento direto dos nossos especialistas seniores.',
    category: 'estrategia',
    tag: 'Exclusivo',
    highlights: ['Diagnóstico Completo de Aquisição', 'Plano de Ação Direcionado', 'Revisão de Oferta e Precificação', 'Acesso Direto aos Especialistas'],
    deliverables: ['Gravação das reuniões estratégicas', 'Documento de diagnóstico detalhado', 'Checklist de implementação', 'Suporte prioritário via WhatsApp'],
    recommendedFor: 'CEOs, diretores e gestores que precisam de clareza estratégica.',
    iconName: 'Compass',
  },
];

export const LAWYER_VIDEO_TESTIMONIALS: VideoTestimonial[] = [
  {
    id: 'dra-dina-neres',
    name: 'Dra. Dina Neres',
    role: 'Advogada',
    specialty: 'Direito & Palestras Estratégicas',
    serviceCategory: 'Funil de Palestra & Tráfego Pago',
    highlightQuote: 'A estruturação do funil de palestras e a estratégia de tráfego pago nos deram clareza, previsibilidade e máxima autoridade diante do nosso público.',
    fullDescription: 'Depoimento em vídeo da Dra. Dina Neres detalhando como a parceria com a CodeEngine estruturou a atração qualificada e a entrega do funil de palestras.',
    thumbnailUrl: '/videos/dra-dina-neres-thumb.jpg',
    videoUrl: '/videos/dra-dina-neres.mp4',
    isFeatured: true,
    duration: '0:53',
  },
];

export const AGENCY_TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Manuel Francisco',
    role: 'CEO & Fundador',
    company: 'MF Empreendimentos Imobiliários',
    location: 'Luanda, Angola 🇦🇴',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    results: '+18.4M Kz em Vendas',
    content: 'A Codeengine revolucionou nossa captação. O funil de palestras e os anúncios segmentados no Meta Ads lotaram nossa masterclass de investimentos em Luanda. Em menos de 45 dias batemos nossa meta trimestral.',
    service: 'Funil de Palestras & Tráfego Pago',
  },
  {
    id: '2',
    name: 'Carla Beatriz Mendes',
    role: 'Diretora Comercial',
    company: 'Nexus Odontologia Integrada',
    location: 'São Paulo, Brasil 🇧🇷',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    results: '4.8x de Retorno (ROAS)',
    content: 'Estávamos queimando orçamento com outra agência que só gerava curiosos. A Codeengine refez nossa landing page e reestruturou as campanhas no Google Ads. Hoje recebemos diariamente pacientes de alto poder aquisitivo no WhatsApp.',
    service: 'Landing Page + Tráfego Pago',
  },
  {
    id: '3',
    name: 'Gonçalo Ribeiro',
    role: 'Managing Partner',
    company: 'Vanguard Tech Advisors',
    location: 'Lisboa, Portugal 🇵🇹',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    results: '+120 Leads B2B Qualificados/mês',
    content: 'A qualidade dos vídeos estratégicos e o direcionamento de anúncios para diretores executivos na Europa nos colocou em outro patamar de autoridade. O sistema de gestão integrado deixa tudo transparente.',
    service: 'Gestão 360° & Edição de Vídeos',
  },
  {
    id: '4',
    name: 'Eunice Domingos',
    role: 'Mentora de Carreira e Liderança',
    company: 'Instituto Protagonismo Feminino',
    location: 'Benguela, Angola 🇦🇴',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    rating: 5,
    results: '98% das Vagas Preenchidas',
    content: 'Fazer o lançamento da minha mentoria com a equipe da Codeengine foi a melhor decisão. Criaram uma landing page impecável e um funil no WhatsApp que converteu acima de qualquer expectativa anterior.',
    service: 'Funil de Vendas & Landing Page',
  },
];

export const AGENCY_METRICS = [
  { value: '+100+', label: 'Operações Ativas', sublabel: 'Projetos e contas gerenciadas' },
  { value: '4.6x', label: 'ROAS Médio', sublabel: 'Retorno médio sobre investimento' },
  { value: '+120k', label: 'Leads Qualificados', sublabel: 'Contatos e oportunidades geradas' },
  { value: '98.7%', label: 'Taxa de Satisfação', sublabel: 'Retenção e aprovação de clientes' },
];

export const HOW_IT_WORKS_STEPS = [
  {
    step: '01',
    title: 'Diagnóstico & Alinhamento',
    description: 'Analisamos profundamente seu produto, público-alvo, histórico de vendas e metas para desenhar a estratégia ideal.',
    badge: 'Passo 1',
    timeline: 'Conclusão em até 24h',
  },
  {
    step: '02',
    title: 'Construção da Estrutura',
    description: 'Montamos a landing page, configuramos os pixels de conversão, editamos os vídeos e criativos estratégicos e preparamos os funis no WhatsApp.',
    badge: 'Passo 2',
    timeline: 'Entrega em 48h a 72h',
  },
  {
    step: '03',
    title: 'Lançamento & Otimização Diária',
    description: 'Colocamos as campanhas no ar, testamos públicos e criativos em tempo real para baixar o custo por aquisição e maximizar o retorno.',
    badge: 'Passo 3',
    timeline: 'Acompanhamento Diário',
  },
  {
    step: '04',
    title: 'Escala & Faturamento Previsível',
    description: 'Identificados os anúncios vencedores, aumentamos os investimentos com segurança para multiplicar seu faturamento e margem de lucro.',
    badge: 'Passo 4',
    timeline: 'Escala Contínua & Semanal',
  },
];

export const FAQ_ITEMS = [
  {
    question: 'Quanto tempo demora para os anúncios começarem a gerar resultados?',
    answer: 'Normalmente, após a aprovação da estrutura técnica e criativos (que leva de 3 a 5 dias úteis), os primeiros leads qualificados começam a chegar no seu WhatsApp nas primeiras 24 a 48 horas após a ativação dos anúncios.',
  },
  {
    question: 'Como funciona o Funil de Palestras & Eventos?',
    answer: 'Montamos toda a esteira: anúncios convidando para a palestra ou webinar, landing page de inscrição rápida, grupo no WhatsApp com mensagens de aquecimento e lembretes automáticos no dia do evento para garantir máxima presença e conversão.',
  },
  {
    question: 'Como acompanho os resultados das campanhas?',
    answer: 'Você terá total transparência: relatórios periódicos de desempenho, acesso ao painel de métricas e reuniões de alinhamento com os gestores responsáveis pela sua conta.',
  },
  {
    question: 'Como funciona a edição de vídeos e criação das páginas?',
    answer: 'Nossa equipe desenvolve a landing page do zero e cuida da edição completa dos vídeos (cortes dinâmicos, legendas animadas, sonoplastia e ganchos de alta retenção para anúncios).',
  },
];
